# fwdteam <fwdteam.github.io>
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GABGMCMAB2DNGTOY5HDOJXX2L7XGZ2AGDR6FYPKV3EHE4XYW7SJNTHEB"
]

[DOCUMENTATION]
ORG_NAME="fwdteam"
ORG_URL="https://fwdteam.github.io"
ORG_LOGO = "https://fwdteam.github.io/img/fwd.png"
ORG_OFFICIAL_EMAIL="fwdteam@yahoo.com"
ORG_SUPPORT_EMAIL="fwdteam@yahoo.com"
ORG_TWITTER="0xfwdteam"
ORG_DESCRIPTION="fwdteam: Create Value to NFT Space"

[[PRINCIPALS]]
email="fwdteam@yahoo.com"

[[CURRENCIES]]
code = "FWD"
name = "FWD"
issuer = "GABGMCMAB2DNGTOY5HDOJXX2L7XGZ2AGDR6FYPKV3EHE4XYW7SJNTHEB"
is_asset_anchored=false
display_decimals = 7
desc="This is token of FWD."
image="https://fwdteam.github.io/img/fwd.png"
conditions="There will only ever be 1 billion FWD tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000
